import {
  Currency,
  Level,
  Prisma,
  PrismaClient,
  SalaryPeriod,
} from "@prisma/client";

import { normalizeCompanyName, normalizeRole } from "../src/utils/normalize";
import {
  annualizeBaseSalary,
  calculateTotalCompensation,
} from "../src/utils/salary";

const prisma = new PrismaClient();

type SeedEntry = {
  submitter: string;
  company: string;
  role: string;
  level: Level;
  city: string;
  state: string;
  country: string;
  currency: Currency;
  salaryPeriod: SalaryPeriod;
  baseSalary: number;
  bonus: number;
  stock: number;
  yearsOfExperience: number;
};

const submitterAnonymousIds = [
  "seed-browser-01",
  "seed-browser-02",
  "seed-browser-03",
  "seed-browser-04",
  "seed-browser-05",
  "seed-browser-06",
];

const entries: SeedEntry[] = [
  {
    submitter: "seed-browser-01",
    company: "Google",
    role: "Software Engineer",
    level: Level.INTERN,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.MONTHLY,
    baseSalary: 30000,
    bonus: 50000,
    stock: 0,
    yearsOfExperience: 0,
  },
  {
    submitter: "seed-browser-02",
    company: "Google",
    role: "Backend Engineer",
    level: Level.L1,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.MONTHLY,
    baseSalary: 85000,
    bonus: 180000,
    stock: 250000,
    yearsOfExperience: 1.5,
  },
  {
    submitter: "seed-browser-03",
    company: "Google",
    role: "Backend Engineer",
    level: Level.L2,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 1800000,
    bonus: 250000,
    stock: 450000,
    yearsOfExperience: 3.5,
  },
  {
    submitter: "seed-browser-04",
    company: "Google",
    role: "Data Engineer",
    level: Level.L3,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 2400000,
    bonus: 350000,
    stock: 700000,
    yearsOfExperience: 6,
  },
  {
    submitter: "seed-browser-05",
    company: "Google",
    role: "Product Manager",
    level: Level.SENIOR,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 3200000,
    bonus: 500000,
    stock: 1100000,
    yearsOfExperience: 9,
  },
  {
    submitter: "seed-browser-06",
    company: "Google",
    role: "Software Engineer",
    level: Level.STAFF,
    city: "Seattle",
    state: "Washington",
    country: "USA",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 215000,
    bonus: 30000,
    stock: 180000,
    yearsOfExperience: 11,
  },
  {
    submitter: "seed-browser-01",
    company: "Microsoft",
    role: "Backend Engineer",
    level: Level.L1,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.MONTHLY,
    baseSalary: 90000,
    bonus: 200000,
    stock: 300000,
    yearsOfExperience: 2,
  },
  {
    submitter: "seed-browser-02",
    company: "Microsoft",
    role: "Backend Engineer",
    level: Level.L2,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 2100000,
    bonus: 300000,
    stock: 600000,
    yearsOfExperience: 4,
  },
  {
    submitter: "seed-browser-03",
    company: "Microsoft",
    role: "DevOps Engineer",
    level: Level.SENIOR,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 2900000,
    bonus: 400000,
    stock: 800000,
    yearsOfExperience: 8,
  },
  {
    submitter: "seed-browser-04",
    company: "Microsoft",
    role: "Data Engineer",
    level: Level.L3,
    city: "Seattle",
    state: "Washington",
    country: "USA",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 175000,
    bonus: 25000,
    stock: 95000,
    yearsOfExperience: 6.5,
  },
  {
    submitter: "seed-browser-05",
    company: "Microsoft",
    role: "Engineering Manager",
    level: Level.PRINCIPAL,
    city: "Redmond",
    state: "Washington",
    country: "USA",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 240000,
    bonus: 45000,
    stock: 220000,
    yearsOfExperience: 14,
  },
  {
    submitter: "seed-browser-06",
    company: "Amazon",
    role: "Backend Engineer",
    level: Level.L1,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.MONTHLY,
    baseSalary: 100000,
    bonus: 150000,
    stock: 350000,
    yearsOfExperience: 1,
  },
  {
    submitter: "seed-browser-01",
    company: "Amazon",
    role: "Backend Engineer",
    level: Level.L2,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 2300000,
    bonus: 350000,
    stock: 900000,
    yearsOfExperience: 4.5,
  },
  {
    submitter: "seed-browser-02",
    company: "Amazon",
    role: "Product Manager",
    level: Level.SENIOR,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 3500000,
    bonus: 600000,
    stock: 1400000,
    yearsOfExperience: 10,
  },
  {
    submitter: "seed-browser-03",
    company: "Amazon",
    role: "Software Engineer",
    level: Level.L3,
    city: "New York",
    state: "New York",
    country: "USA",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 190000,
    bonus: 30000,
    stock: 130000,
    yearsOfExperience: 7,
  },
  {
    submitter: "seed-browser-04",
    company: "Amazon",
    role: "Engineering Manager",
    level: Level.STAFF,
    city: "Seattle",
    state: "Washington",
    country: "USA",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 225000,
    bonus: 40000,
    stock: 200000,
    yearsOfExperience: 12,
  },
  {
    submitter: "seed-browser-05",
    company: "Atlassian",
    role: "Software Engineer",
    level: Level.L1,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.MONTHLY,
    baseSalary: 80000,
    bonus: 120000,
    stock: 300000,
    yearsOfExperience: 1.5,
  },
  {
    submitter: "seed-browser-06",
    company: "Atlassian",
    role: "Product Manager",
    level: Level.L2,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 2000000,
    bonus: 250000,
    stock: 550000,
    yearsOfExperience: 4,
  },
  {
    submitter: "seed-browser-01",
    company: "Atlassian",
    role: "Data Engineer",
    level: Level.SENIOR,
    city: "Sydney",
    state: "New South Wales",
    country: "Australia",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 160000,
    bonus: 20000,
    stock: 85000,
    yearsOfExperience: 8,
  },
  {
    submitter: "seed-browser-02",
    company: "Atlassian",
    role: "DevOps Engineer",
    level: Level.STAFF,
    city: "San Francisco",
    state: "California",
    country: "USA",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 205000,
    bonus: 30000,
    stock: 175000,
    yearsOfExperience: 11,
  },
  {
    submitter: "seed-browser-03",
    company: "Infosys",
    role: "Software Engineer",
    level: Level.L1,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.MONTHLY,
    baseSalary: 45000,
    bonus: 50000,
    stock: 0,
    yearsOfExperience: 1,
  },
  {
    submitter: "seed-browser-04",
    company: "Infosys",
    role: "Backend Engineer",
    level: Level.L2,
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 1100000,
    bonus: 100000,
    stock: 0,
    yearsOfExperience: 3,
  },
  {
    submitter: "seed-browser-05",
    company: "Infosys",
    role: "Data Engineer",
    level: Level.L3,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 1600000,
    bonus: 180000,
    stock: 100000,
    yearsOfExperience: 5.5,
  },
  {
    submitter: "seed-browser-06",
    company: "Infosys",
    role: "Engineering Manager",
    level: Level.SENIOR,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    currency: Currency.INR,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 2500000,
    bonus: 300000,
    stock: 250000,
    yearsOfExperience: 9.5,
  },
  {
    submitter: "seed-browser-01",
    company: "Stripe",
    role: "Backend Engineer",
    level: Level.L2,
    city: "Dublin",
    state: "Leinster",
    country: "Ireland",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 155000,
    bonus: 18000,
    stock: 90000,
    yearsOfExperience: 4,
  },
  {
    submitter: "seed-browser-02",
    company: "Stripe",
    role: "Backend Engineer",
    level: Level.L3,
    city: "San Francisco",
    state: "California",
    country: "USA",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 210000,
    bonus: 30000,
    stock: 160000,
    yearsOfExperience: 7.5,
  },
  {
    submitter: "seed-browser-03",
    company: "Stripe",
    role: "Product Manager",
    level: Level.SENIOR,
    city: "New York",
    state: "New York",
    country: "USA",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 230000,
    bonus: 35000,
    stock: 190000,
    yearsOfExperience: 10,
  },
  {
    submitter: "seed-browser-04",
    company: "Stripe",
    role: "Engineering Manager",
    level: Level.PRINCIPAL,
    city: "San Francisco",
    state: "California",
    country: "USA",
    currency: Currency.USD,
    salaryPeriod: SalaryPeriod.ANNUAL,
    baseSalary: 275000,
    bonus: 50000,
    stock: 300000,
    yearsOfExperience: 15,
  },
];

async function main() {
  // Upserts make supporting records repeatable without deleting developer-created records
  const submitterByAnonymousId = new Map<string, string>();
  for (const anonymousId of submitterAnonymousIds) {
    const submitter = await prisma.anonymousSubmitter.upsert({
      where: { anonymousId },
      create: { anonymousId },
      update: {},
      select: { id: true },
    });
    submitterByAnonymousId.set(anonymousId, submitter.id);
  }

  const companyByNormalizedName = new Map<string, string>();
  for (const companyName of new Set(entries.map((entry) => entry.company))) {
    const nameNormalized = normalizeCompanyName(companyName);
    const company = await prisma.company.upsert({
      where: { nameNormalized },
      create: { nameRaw: companyName, nameNormalized },
      update: {},
      select: { id: true },
    });
    companyByNormalizedName.set(nameNormalized, company.id);
  }

  // Use the production normalization and salary helpers so seeded records obey the same invariants as API-created records.
  const entryData = entries.map((entry, index) => {
    const baseSalarySubmitted = new Prisma.Decimal(entry.baseSalary);
    const annualBaseSalary = annualizeBaseSalary(
      baseSalarySubmitted,
      entry.salaryPeriod,
    );
    const annualBonus = new Prisma.Decimal(entry.bonus);
    const annualStock = new Prisma.Decimal(entry.stock);

    return {
      companyId: companyByNormalizedName.get(normalizeCompanyName(entry.company))!,
      submitterId: submitterByAnonymousId.get(entry.submitter)!,
      roleRaw: entry.role,
      roleNormalized: normalizeRole(entry.role),
      level: entry.level,
      city: entry.city,
      state: entry.state,
      country: entry.country,
      currency: entry.currency,
      salaryPeriod: entry.salaryPeriod,
      baseSalarySubmitted,
      annualBaseSalary,
      annualBonus,
      annualStock,
      totalCompensation: calculateTotalCompensation(
        annualBaseSalary,
        annualBonus,
        annualStock,
      ),
      yearsOfExperience: new Prisma.Decimal(entry.yearsOfExperience),
      // Fixed timestamps make default sorting and pagination determinstic
      createdAt: new Date(Date.UTC(2025, 0, index + 1)),
    };
  });

  // The composite duplicate constraint makes re-running the seed additive and safe for these fixed records.
  const result = await prisma.compensationEntry.createMany({
    data: entryData,
    skipDuplicates: true,
  });

  console.log(
    `Seed complete: ${result.count} entries inserted from ${entries.length} deterministic records.`,
  );
}

main()
  .catch((error) => {
    console.error("Seed failed", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
